name: wqufp
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4
  - asttokens=3.0.0
  - autopep8=2.3.2
  - beautifulsoup4=4.13.5
  - black=25.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - certifi=2025.8.3
  - cffi=1.17.1
  - cfgv=3.3.1
  - charset-normalizer=3.4.3
  - click=8.2.1
  - contourpy=1.3.3
  - cycler=0.12.1
  - decorator=5.2.1
  - distlib=0.4.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - filelock=3.19.1
  - flake8=7.3.0
  - fonttools=4.59.2
  - fredapi=0.5.2
  - freetype=2.14.1
  - frozendict=2.4.6
  - h2=4.3.0
  - hpack=4.1.0
  - html5lib=1.1
  - hyperframe=6.1.0
  - icu=75.1
  - identify=2.6.14
  - idna=3.10
  - importlib-metadata=8.7.0
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - isort=6.0.1
  - jedi=0.19.2
  - joblib=1.5.2
  - kiwisolver=1.4.9
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=21.1.1
  - libdeflate=1.24
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsqlite=3.50.4
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.0
  - lxml=6.0.1
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mccabe=0.7.0
  - multitasking=0.0.12
  - munkres=1.1.4
  - mypy=1.18.1
  - mypy_extensions=1.1.0
  - nbqa=1.9.0
  - ncurses=6.5
  - nodeenv=1.9.1
  - numpy=2.3.3
  - openjpeg=2.5.3
  - openssl=3.5.2
  - packaging=25.0
  - pandas=2.3.2
  - parso=0.8.5
  - pathspec=0.12.1
  - patsy=1.0.1
  - peewee=3.18.2
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - platformdirs=4.4.0
  - pre-commit=4.3.0
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycodestyle=2.14.0
  - pycparser=2.22
  - pyflakes=3.4.0
  - pygments=2.19.2
  - pyparsing=3.2.4
  - pysocks=1.7.1
  - python=3.13.7
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.1
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyyaml=6.0.2
  - qhull=2020.2
  - readline=8.2
  - requests=2.32.5
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - soupsieve=2.8
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tokenize-rt=6.2.0
  - tomli=2.2.1
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ukkonen=1.0.1
  - urllib3=2.5.0
  - virtualenv=20.34.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - yfinance=0.2.57
  - zipp=3.23.0
  - zstandard=0.25.0
  - zstd=1.5.7
