name: Pre-commit Checks

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pre-commit
          pip install nbqa black flake8 isort mypy

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
